require:
  - rubocop-minitest
  - rubocop-performance
inherit_from:
  - rubocop.yml

AllCops:
  NewCops: enable

Layout/HashAlignment:
  Enabled: false
Naming/MethodName:
  Enabled: false
Layout/LineLength:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false

